### ISSUE TITLE
Question for predict about new sentence

### ISSUE THREAD

**Issue by blackbirt-5** [ruiantunes/biocreative-vi-track-5-chemprot#2]
Hi,

Your task using chemprot is very useful to me.
I have a question for using your task.
How can I predict for the new abstract sentence of pudmed?

Best Regards,
From Simon (SH) Oh

**Comment by ruiantunes** [comment]
Hi @blackbirt-5, thank you for question. The code as it is does not provide a friendly command for predicting relations for a new abstract.
